### ISSUE TITLE
compile Development tools error on MacOs m3

### ISSUE THREAD

**Issue by luoliwoshang** [goplus/llgo#310]
When I install LLGO from the source code, I am ready to compile the development tool as follows
https://github.com/goplus/llgo/blob/f3b6d25aaa5991cc55b9967b87a6639a409eb73c/README.md?plain=1#L241-L256

and install and compile cjson as follows

https://github.com/goplus/llgo/blob/f3b6d25aaa5991cc55b9967b87a6639a409eb73c/c/cjson/README.md?plain=1#L9-L20
```bash
 sudo make install
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/include/cjson/cJSON.h
-- Up-to-date: /usr/local/lib/pkgconfig/libcjson.pc
-- Up-to-date: /usr/local/lib/libcjson.1.7.18.dylib
-- Up-to-date: /usr/local/lib/libcjson.1.dylib
-- Up-to-date: /usr/local/lib/libcjson.dylib
-- Up-to-date: /usr/local/lib/cmake/cJSON/cjson.cmake
-- Up-to-date: /usr/local/lib/cmake/cJSON/cjson-noconfig.cmake
-- Up-to-date: /usr/local/lib/cmake/cJSON/cJSONConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/cJSON/cJSONConfigVersion.cmake
```
Remind me of the following error
```bash
llgo on  main [$?] via 🐹 v1.20.14 via 🐍 v3.12.3 
❯ cd chore/_xtool

llgo/chore/_xtool on  main [$?] 
❯ llgo install ./... 
panic: test link args ' cjson' failed
        expanded to: cjson
        resolved to:  -l cjson
        error: ld: library 'cjson' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)


goroutine 1 [running]:
github.com/goplus/llgo/internal/build.buildAllPkgs(0x140001db680, {0x14005037ba0?, 0x140001941a0?, 0x1?}, 0x1?, 0x104fdf580?, 0x88?)
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/internal/build/build.go:252 +0x634
github.com/goplus/llgo/internal/build.Do({0x140001941a0?, 0x10508b9b0?, 0x7?}, 0x14000181630)
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/internal/build/build.go:148 +0x3b4
github.com/goplus/llgo/cmd/internal/install.runCmd(0x140001b2120?, {0x140001941a0, 0x1, 0x1})
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/cmd/internal/install/install.go:37 +0x40
main.main()
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/cmd/llgo/llgo.go:87 +0x4c8
```
Running `llgo/c/cjson/_demo/mkjson` will have the same problem.
```bash
cjson/_demo/mkjson on  main [$?] via 🐹 v1.20.14 
❯ llgo run .         
panic: test link args ' cjson' failed
        expanded to: cjson
        resolved to:  -l cjson
        error: ld: library 'cjson' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)


goroutine 1 [running]:
github.com/goplus/llgo/internal/build.buildAllPkgs(0x14000165680, {0x14004f18a18?, 0x1400011a1a0?, 0x1?}, 0x1?, 0x103037580?, 0x70?)
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/internal/build/build.go:252 +0x634
github.com/goplus/llgo/internal/build.Do({0x1400011a1a0?, 0x1?, 0x1?}, 0x140001595e0)
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/internal/build/build.go:148 +0x3b4
github.com/goplus/llgo/cmd/internal/run.runCmd(0x14000138120?, {0x1400011a1a0?, 0x1400005c6e8?, 0x10304c6a4?})
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/cmd/internal/run/run.go:47 +0xa0
main.main()
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/cmd/llgo/llgo.go:87 +0x4c8
```
Running `llgo/c/cjson/_demo/mkjson` will have the same problem.
```bash
cjson/_demo/mkjson on  main [$?] via 🐹 v1.20.14 
❯ llgo run .         
panic: test link args ' cjson' failed
        expanded to: cjson
        resolved to:  -l cjson
        error: ld: library 'cjson' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)


goroutine 1 [running]:
github.com/goplus/llgo/internal/build.buildAllPkgs(0x14000165680, {0x14004f18a18?, 0x1400011a1a0?, 0x1?}, 0x1?, 0x103037580?, 0x70?)
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/internal/build/build.go:252 +0x634
github.com/goplus/llgo/internal/build.Do({0x1400011a1a0?, 0x1?, 0x1?}, 0x140001595e0)
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/internal/build/build.go:148 +0x3b4
github.com/goplus/llgo/cmd/internal/run.runCmd(0x14000138120?, {0x1400011a1a0?, 0x1400005c6e8?, 0x10304c6a4?})
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/cmd/internal/run/run.go:47 +0xa0
main.main()
        /Users/zhangzhiyang/Documents/Code/goplus/llgo/cmd/llgo/llgo.go:87 +0x4c8
```
Environment
---
mac version: MacOS 14.2 M3 MacBook Pro (2023)
```bash
uname -a
Darwin ... 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:55 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8122 arm64
```
```bash
clang -v 
Homebrew clang version 17.0.6
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm@17/bin
```
```
go version      
go version go1.20.14 darwin/arm64
```

**Comment by luoliwoshang** [comment]
将cjson编译到的目录，添加到`C_INCLUDE_PATH`以及`LIBRARY_PATH`后
```bash
❯ echo $LIBRARY_PATH
/usr/local/lib
❯ echo $C_INCLUDE_PATH
/usr/local/include
```
出现如下问题
```bash
cjson/_demo/mkjson 
❯ llgo run .
dyld[83314]: Library not loaded: @rpath/libcjson.1.dylib
  Referenced from: <34BD49FB-471B-3D79-A84A-FBC2F5AB4653> /Users/zhangzhiyang/go/bin/mkjson
  Reason: no LC_RPATH's found
```
